In [4]:
import pandas as pd

In [6]:
ds_divipola = pd.read_csv("../kit/data/raw/divipola.csv")

In [7]:
ds_divipola.info

<bound method DataFrame.info of       Código Departamento Nombre Departamento  Código Municipio  \
0                       5           ANTIOQUIA              5001
1                       5           ANTIOQUIA              5002
2                       5           ANTIOQUIA              5004
3                       5           ANTIOQUIA              5021
4                       5           ANTIOQUIA              5030
...                   ...                 ...               ...
1117                   97              VAUPÉS             97889
1118                   99             VICHADA             99001
1119                   99             VICHADA             99524
1120                   99             VICHADA             99624
1121                   99             VICHADA             99773

     Nombre Municipio Tipo: Municipio / Isla / Área no municipalizada  \
0            MEDELLÍN                                       Municipio
1           ABEJORRAL                                       Municipio
2            ABRIAQUÍ                                       Municipio
3          ALEJANDRÍA                                       Municipio
4               AMAGÁ                                       Municipio
...               ...                                             ...
1117         YAVARATÉ                          Área no municipalizada
1118   PUERTO CARREÑO                                       Municipio
1119     LA PRIMAVERA                                       Municipio
1120    SANTA ROSALÍA                                       Municipio
1121         CUMARIBO                                       Municipio

        longitud   Latitud
0     -75,581775  6,246631
1     -75,428739  5,789315
2     -76,064304  6,632282
3     -75,141346  6,376061
4     -75,702188  6,038708
...          ...       ...
1117  -69,203337  0,609142
1118  -67,487095  6,186636
1119  -70,410515  5,486309
1120  -70,859499  5,136393
1121  -69,795533  4,446352

[1122 rows x 7 columns]>

In [8]:
ds_divipola.describe()

       Código Departamento  Código Municipio
count          1122.000000       1122.000000
mean             38.222816      38656.544563
std              26.538214      26524.369769
min               5.000000       5001.000000
25%              15.000000      15677.250000
50%              25.000000      25840.000000
75%              66.000000      66452.000000
max              99.000000      99773.000000

In [9]:
ds_divipola.isna().sum()

Código Departamento                                0
Nombre Departamento                                0
Código Municipio                                   0
Nombre Municipio                                   0
Tipo: Municipio / Isla / Área no municipalizada    0
longitud                                           0
Latitud                                            0
dtype: int64

In [10]:
ds_divipola.isnull().sum

<bound method DataFrame.sum of       Código Departamento  Nombre Departamento  Código Municipio  \
0                   False                False             False
1                   False                False             False
2                   False                False             False
3                   False                False             False
4                   False                False             False
...                   ...                  ...               ...
1117                False                False             False
1118                False                False             False
1119                False                False             False
1120                False                False             False
1121                False                False             False

      Nombre Municipio  Tipo: Municipio / Isla / Área no municipalizada  \
0                False                                            False
1                False                                            False
2                False                                            False
3                False                                            False
4                False                                            False
...                ...                                              ...
1117             False                                            False
1118             False                                            False
1119             False                                            False
1120             False                                            False
1121             False                                            False

      longitud  Latitud
0        False    False
1        False    False
2        False    False
3        False    False
4        False    False
...        ...      ...
1117     False    False
1118     False    False
1119     False    False
1120     False    False
1121     False    False

[1122 rows x 7 columns]>

In [12]:
ds_agrosavia = pd.read_csv("../kit/data/raw/agrosavia.csv", dtype=str)

In [15]:
ds_agrosavia.info

<bound method DataFrame.info of       Secuencial Fecha de Análisis Departamento             Municipio  \
0              1         7/01/2014       NARIÑO  SAN ANDRÉS DE TUMACO
1              2        21/08/2014        HUILA           SANTA MARÍA
2              3        22/08/2014    ANTIOQUIA              LIBORINA
3              4        22/08/2014    ANTIOQUIA              LIBORINA
4              5        22/08/2014    ANTIOQUIA              LIBORINA
...          ...               ...          ...                   ...
92733      92734         7/04/2025    SANTANDER               SOCORRO
92734      92735         4/04/2025    SANTANDER    PALMAS DEL SOCORRO
92735      92736         3/04/2025    SANTANDER    PALMAS DEL SOCORRO
92736      92737         4/04/2025    SANTANDER    PALMAS DEL SOCORRO
92737      92738         4/04/2025    SANTANDER    PALMAS DEL SOCORRO

          Cultivo          Estado Tiempo de establecimiento  \
0       No Indica       No indica                 No indica
1      Granadilla     Establecido             De 1 a 5 años
2            Café  Por establecer                 No indica
3        Maracuyá  Por establecer                 No indica
4            Café  Por establecer                 No indica
...           ...             ...                       ...
92733       Cacao     ESTABLECIDO              De 0 a 1 año
92734       Cacao     ESTABLECIDO            de 5 a 10 años
92735       Cacao     ESTABLECIDO            mas de 10 años
92736       Cacao     ESTABLECIDO             de 1 a 5 años
92737       Cacao     ESTABLECIDO            de 5 a 10 años

                 Topografia          Drenaje      Riego  ...  \
0                 No indica        No indica  No indica  ...
1                 Pendiente     Buen drenaje   No Tiene  ...
2                 Pendiente      Mal drenaje   No Tiene  ...
3                  Ondulado      Mal drenaje   No Tiene  ...
4                  Ondulado      Mal drenaje   No Tiene  ...
...                     ...              ...        ...  ...
92733  Ligeramente ondulado  Regular drenaje      Goteo  ...
92734  Ligeramente ondulado     Buen drenaje  No indica  ...
92735                 Plano  Regular drenaje  No indica  ...
92736    Pendiente moderada     Buen drenaje  No indica  ...
92737                 Plano     Buen drenaje  No indica  ...

      Conductividad electrica Hierro disponible olsen Cobre disponible  \
0                       0.133                   66.39            1.700
1                       2.749                   250.9              3.7
2                       0.328                     390            11.10
3                       0.171                     200              4.2
4                       0.323                   117.9              3.8
...                       ...                     ...              ...
92733                    0.21                  418.40            <1.00
92734                    0.11                  226.75            <1.00
92735                    0.12                  346.93             1.69
92736                    0.13                  292.22            <1.00
92737                    0.18                  331.71            <1.00

      Manganeso disponible Olsen Zinc disponible Olsen Boro disponible  \
0                          1.700                   1.5           0.187
1                           29.4                 28.70           2.084
2                          8.299                     5           0.085
3                          4.699                     1           0.229
4                          4.600                 0.700           0.139
...                          ...                   ...             ...
92733                       2.62                  1.63            0.29
92734                       1.33                 <1.00            0.16
92735                      10.34                  1.95            0.12
92736                       4.01                  1.34            0.17
92737                       2.32                  1.12            0.35

      Hierro disponible doble acido Cobre disponible doble acido  \
0                                ND                           ND
1                                ND                           ND
2                                ND                           ND
3                                ND                           ND
4                                ND                           ND
...                             ...                          ...
92733                            ND                           ND
92734                            ND                           ND
92735                            ND                           ND
92736                            ND                           ND
92737                            ND                           ND

      Manganeso disponible doble acido Zinc disponible doble  acido
0                                   ND                           ND
1                                   ND                           ND
2                                   ND                           ND
3                                   ND                           ND
4                                   ND                           ND
...                                ...                          ...
92733                               ND                           ND
92734                               ND                           ND
92735                               ND                           ND
92736                               ND                           ND
92737                               ND                           ND

[92738 rows x 32 columns]>

In [16]:
ds_agrosavia.describe()

,Secuencial,Fecha de Análisis,Departamento,Municipio,Cultivo,Estado,Tiempo de establecimiento,Topografia,Drenaje,Riego,...,Conductividad electrica,Hierro disponible olsen,Cobre disponible,Manganeso disponible Olsen,Zinc disponible Olsen,Boro disponible,Hierro disponible doble acido,Cobre disponible doble acido,Manganeso disponible doble acido,Zinc disponible doble acido
count,92738,92738,92738,92736,92738,92738,92738,92738,92738,92738,...,92738,92738,92738,92738,92738,92738,92737,92738,92738,92738
unique,92738,2388,33,990,282,4,9,13,6,17,...,3567,36134,7060,11363,8648,1903,3212,1075,2565,1498
top,92738,5/08/2016,CUNDINAMARCA,VILLAVICENCIO,Cacao,Por establecer,De 0 a 1 año,Plano,Buen drenaje,No Tiene,...,0.21,ND,<1.00,ND,<1.00,0.11,ND,ND,ND,ND
freq,1,685,14016,2165,11104,33138,35644,30656,49807,41159,...,1790,5872,13832,5872,19301,1430,87951,87952,87952,87952

In [22]:
ds_agrosavia.isna().sum()

Secuencial                            0
Fecha de Análisis                     0
Departamento                          0
Municipio                             2
Cultivo                               0
Estado                                0
Tiempo de establecimiento             0
Topografia                            0
Drenaje                               0
Riego                                 0
Fertilizantes aplicados               0
pH agua:suelo                         0
Materia organica                      0
Fósforo Bray II                       0
Azufre Fosfato monocalcico            0
Acidez Intercambiable                 0
Aluminio intercambiable               0
Calcio intercambiable                 0
Magnesio intercambiable               0
Potasio intercambiable                0
Sodio intercambiable                  0
capacidad de intercambio cationico    0
Conductividad electrica               0
Hierro disponible olsen               0
Cobre disponible                      0
Manganeso disponible Olsen            0
Zinc disponible Olsen                 0
Boro disponible                       0
Hierro disponible doble acido         1
Cobre disponible doble acido          0
Manganeso disponible doble acido      0
Zinc disponible doble  acido          0
dtype: int64

In [23]:
ds_agrosavia.isnull().sum()

Secuencial                            0
Fecha de Análisis                     0
Departamento                          0
Municipio                             2
Cultivo                               0
Estado                                0
Tiempo de establecimiento             0
Topografia                            0
Drenaje                               0
Riego                                 0
Fertilizantes aplicados               0
pH agua:suelo                         0
Materia organica                      0
Fósforo Bray II                       0
Azufre Fosfato monocalcico            0
Acidez Intercambiable                 0
Aluminio intercambiable               0
Calcio intercambiable                 0
Magnesio intercambiable               0
Potasio intercambiable                0
Sodio intercambiable                  0
capacidad de intercambio cationico    0
Conductividad electrica               0
Hierro disponible olsen               0
Cobre disponible                      0
Manganeso disponible Olsen            0
Zinc disponible Olsen                 0
Boro disponible                       0
Hierro disponible doble acido         1
Cobre disponible doble acido          0
Manganeso disponible doble acido      0
Zinc disponible doble  acido          0
dtype: int64

In [17]:
primer_campo_agrosavia = ds_agrosavia.columns[0]

In [19]:
p_numerico_agrosavia = pd.to_numeric(ds_agrosavia[primer_campo_agrosavia].str.strip(), errors="coerce")

In [26]:
ds_agrosavia.columns

Index(['Secuencial', 'Fecha de Análisis', 'Departamento', 'Municipio',
       'Cultivo', 'Estado', 'Tiempo de establecimiento', 'Topografia',
       'Drenaje', 'Riego', 'Fertilizantes aplicados', 'pH agua:suelo',
       'Materia organica', 'Fósforo Bray II', 'Azufre Fosfato monocalcico',
       'Acidez Intercambiable', 'Aluminio intercambiable',
       'Calcio intercambiable', 'Magnesio intercambiable',
       'Potasio intercambiable', 'Sodio intercambiable',
       'capacidad de intercambio cationico', 'Conductividad electrica',
       'Hierro disponible olsen', 'Cobre disponible',
       'Manganeso disponible Olsen', 'Zinc disponible Olsen',
       'Boro disponible', 'Hierro disponible doble acido',
       'Cobre disponible doble acido', 'Manganeso disponible doble acido',
       'Zinc disponible doble  acido'],
      dtype='object')

In [27]:
ds_agrosavia_seg = pd.read_csv('../kit/data/raw/agrosavia.csv', usecols=["Tiempo de establecimiento", "Cultivo", "Estado"])

In [28]:
ds_agrosavia_seg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92738 entries, 0 to 92737
Data columns (total 3 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Cultivo                    92738 non-null  object
 1   Estado                     92738 non-null  object
 2   Tiempo de establecimiento  92738 non-null  object
dtypes: object(3)
memory usage: 2.1+ MB

In [29]:
for column in ds_agrosavia_seg.columns:
    try:
        issue_column = pd.read_csv('../data/raw/agrosavia.csv', usecols=[column])
    except:
        print('issue', column)

issue Cultivo
issue Estado
issue Tiempo de establecimiento

In [20]:
municipios = (
    ds_agrosavia["Municipio"]
    .dropna()
    .str.strip()
    .loc[lambda s: s.ne("")]
    .drop_duplicates()
    .sort_values()
    .reset_index(drop=True)
)

In [21]:
display(municipios)

0      ABEJORRAL
1       ABRIAQUÍ
2        ACACÍAS
3         ACANDÍ
4        ACEVEDO
         ...
985    bOCHALEMA
986       ÁBREGO
987       ÍQUIRA
988       ÚMBITA
989        ÚTICA
Name: Municipio, Length: 990, dtype: object